/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theatergui;

import javax.swing.JOptionPane;

/**
 *
 * @author DANIEL FAILADONA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form managerLogin
     */
    public Login() {
        initComponents();
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Manager_Login = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Navigation = new javax.swing.JPanel();
        Manager_Login1 = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Navigation1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordML = new javax.swing.JPasswordField();
        MR_clickhere = new javax.swing.JLabel();
        usernameML = new javax.swing.JTextField();
        managerCancel = new javax.swing.JButton();
        ConfirmLM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Manager_Login.setBackground(new java.awt.Color(51, 51, 51));
        Manager_Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 255, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manager Login");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1310, 40));

        Manager_Login.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 100));

        Navigation.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout NavigationLayout = new javax.swing.GroupLayout(Navigation);
        Navigation.setLayout(NavigationLayout);
        NavigationLayout.setHorizontalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        NavigationLayout.setVerticalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        Manager_Login.add(Navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 540));

        Manager_Login1.setBackground(new java.awt.Color(39, 39, 39));
        Manager_Login1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header1.setBackground(new java.awt.Color(0, 0, 0));
        Header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 255, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manager Login");
        Header1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1310, 40));

        Manager_Login1.add(Header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 100));

        Navigation1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Navigation1Layout = new javax.swing.GroupLayout(Navigation1);
        Navigation1.setLayout(Navigation1Layout);
        Navigation1Layout.setHorizontalGroup(
            Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        Navigation1Layout.setVerticalGroup(
            Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        Manager_Login1.add(Navigation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 540));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        Manager_Login1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 80, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        Manager_Login1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 80, 30));

        passwordML.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordMLActionPerformed(evt);
            }
        });
        Manager_Login1.add(passwordML, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 330, 30));

        MR_clickhere.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MR_clickhere.setForeground(new java.awt.Color(255, 255, 255));
        MR_clickhere.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MR_clickhere.setText("Add new owner account? click here");
        MR_clickhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MR_clickhereMouseClicked(evt);
            }
        });
        Manager_Login1.add(MR_clickhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 330, 20));

        usernameML.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameMLActionPerformed(evt);
            }
        });
        Manager_Login1.add(usernameML, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 330, 30));

        managerCancel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        managerCancel.setText("Cancel");
        managerCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerCancelActionPerformed(evt);
            }
        });
        Manager_Login1.add(managerCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 90, 30));

        ConfirmLM.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ConfirmLM.setText("Confirm");
        ConfirmLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmLMActionPerformed(evt);
            }
        });
        Manager_Login1.add(ConfirmLM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 550, 90, 30));

        Manager_Login.add(Manager_Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Manager_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Manager_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void managerCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerCancelActionPerformed
        StartupPanel sp = new StartupPanel();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managerCancelActionPerformed

    private void usernameMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameMLActionPerformed

    private void passwordMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordMLActionPerformed

    private void MR_clickhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MR_clickhereMouseClicked
        Registration r = new Registration();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MR_clickhereMouseClicked

    private void ConfirmLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmLMActionPerformed
        if(usernameML.getText().isEmpty() || passwordML.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Fill All Boxes");

        }
    }//GEN-LAST:event_ConfirmLMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmLM;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header1;
    private javax.swing.JLabel MR_clickhere;
    private javax.swing.JPanel Manager_Login;
    private javax.swing.JPanel Manager_Login1;
    private javax.swing.JPanel Navigation;
    private javax.swing.JPanel Navigation1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton managerCancel;
    private javax.swing.JPasswordField passwordML;
    private javax.swing.JTextField usernameML;
    // End of variables declaration//GEN-END:variables
}
