/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theatergui;

import admin.AdminDashboard;
import admin.U_Admin;
import java.awt.Color;

/**
 *
 * @author DANIEL FAILADONA
 */
public class StartupPanel extends javax.swing.JFrame {

    private Color Hover;
    Color hover = new Color(51,51,255);
    private Color Default1;
    Color Default = new Color(255,255,255);

    /**
     * Creates new form mainMenu
     */
    public StartupPanel() {
        initComponents();
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Navigation = new javax.swing.JPanel();
        ShowMovies = new javax.swing.JButton();
        ManagerStartup = new javax.swing.JButton();
        ShowMovies1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setBackground(new java.awt.Color(39, 39, 39));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 255, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Theater Ticketing System");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1310, 40));

        Main.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 100));

        Navigation.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout NavigationLayout = new javax.swing.GroupLayout(Navigation);
        Navigation.setLayout(NavigationLayout);
        NavigationLayout.setHorizontalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        NavigationLayout.setVerticalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        Main.add(Navigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 540));

        ShowMovies.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ShowMovies.setText("Testing");
        ShowMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShowMoviesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShowMoviesMouseExited(evt);
            }
        });
        ShowMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowMoviesActionPerformed(evt);
            }
        });
        Main.add(ShowMovies, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 230, 50));

        ManagerStartup.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ManagerStartup.setText("Login");
        ManagerStartup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerStartupActionPerformed(evt);
            }
        });
        Main.add(ManagerStartup, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 230, 50));

        ShowMovies1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ShowMovies1.setText("Show Movies");
        ShowMovies1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShowMovies1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShowMovies1MouseExited(evt);
            }
        });
        ShowMovies1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowMovies1ActionPerformed(evt);
            }
        });
        Main.add(ShowMovies1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 1325, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowMoviesActionPerformed
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ShowMoviesActionPerformed

    private void ManagerStartupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerStartupActionPerformed
        Login ml = new Login();
        ml.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManagerStartupActionPerformed

    private void ShowMoviesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMoviesMouseEntered
        ShowMovies.setBackground(hover);
    }//GEN-LAST:event_ShowMoviesMouseEntered

    private void ShowMoviesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMoviesMouseExited
        ShowMovies.setBackground(Default1);
    }//GEN-LAST:event_ShowMoviesMouseExited

    private void ShowMovies1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMovies1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowMovies1MouseEntered

    private void ShowMovies1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMovies1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowMovies1MouseExited

    private void ShowMovies1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowMovies1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShowMovies1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartupPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JButton ManagerStartup;
    private javax.swing.JPanel Navigation;
    private javax.swing.JButton ShowMovies;
    private javax.swing.JButton ShowMovies1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
